### ISSUE TITLE
toaster Problem

### ISSUE THREAD

**Issue by ziadMark** [crops/toaster-container#28]
Hallo,
when i try to run this command on my docker:
docker run -it --rm -p 0.0.0.0:18000:8000 -v myvolume:/workdir crops/toaster

i recieve always the same message:

Unable to find image 'crops/toaster:latest' locally
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: pull access denied for crops/toaster, repository does not exist or may require 'docker login'.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

i have already logged to my docker account

any suggestions please ?

thank you

**Comment by rewitt1** [comment]
Hi @ziadMark,

Sorry about this, but the images have been removed from dockerhub because I no longer had the knowledge and time to continue to make sure they worked with newer releases and distros. The github repo still exists in case a user wants to try to get the images to work on their own, but unless someone else in the Yocto Project can maintain and verify the functionality the images, they won't appear on dockerhub.

However, I should update the README.md to make this clear.

**Comment by moto-timo** [comment]
This has been possible for a while now.
https://hub.docker.com/r/crops/toaster

From time to time, upstream changes in bitbake break us, but we do try to keep things current.
